# Deep Learning - Introduction à Pytorch


## TP1 : Prise en main de Pytorch

Sylvain Lamprier (sylvain.lamprier@univ-angers.fr)

Supports adaptés de Nicolas Baskiotis (nicolas.baskiotis@sorbonne-univeriste.fr) et Benjamin Piwowarski (benjamin.piwowarski@sorbonne-universite.fr) -- MLIA/ISIR, Sorbonne Université



Les lignes suivantes permettent d'importer pytorch et vérifier qu'un GPU est disponible. Il est recommandé d'utiliser un manager d'environnement python type conda pour l'ensemble des tps. Après la création de votre environnement (via  $\texttt{conda create --name <nom_env>}$) et son activation (via $\texttt{conda activate <nom_env>}$), installer pytorch selon la commande donnée sur le site de $\href{https://pytorch.org/}{\texttt{PyTorch}}$  (choisir la version en fonction de votre GPU et sa version de cuda).  

In [5]:
import torch
print("La version de torch est : ",torch.__version__)
print("Le calcul GPU est disponible ? ", torch.cuda.is_available())

import numpy as np
import sklearn


La version de torch est :  2.9.0+cu126
Le calcul GPU est disponible ?  False


### <span class="alert-success"> Exercice : Syntaxe

Le principal objet manipulé sous Pytorch est **torch.Tensor** qui correspond à un tenseur mathématique (généralisation de la notion de matrice en $n$-dimensions), très proche dans l'utilisation de **numpy.array**.   Cet objet est optimisé pour les calculs sur GPU ce qui implique quelques contraintes plus importantes que sous **numpy**. En particulier :
* le type du tenseur manipulé est très important et les conversions ne sont pas automatique (**FloatTensor** de type **torch.float**, **DoubleTensor** de type **torch.double**,  **ByteTensor** de type **torch.byte**, **IntTensor** de type **torch.int**, **LongTensor** de type **torch.long**). Pour un tenseur **t** La conversion se fait très simplement en utilisant les fonctions : **t.double()**, **t.float()**, **t.long()** ...
* la plupart des opérations ont une version *inplace*, c'est-à-dire qui modifie le tenseur plutôt que de renvoyer un nouveau tenseur; elles sont suffixées par **_** (**add_** par exemple).

Donner des exemples d'instructions correspondant aux commentaires ci-dessous. N'hésitez pas à vous référez à la [documentation officielle](https://pytorch.org/docs/stable/tensors.html) pour la liste exhaustive des opérations.


In [6]:
# Création de tenseurs et caractéristiques
## Créer un tenseur (2,3) à partir d'une liste

## Créer un tenseur  tenseur rempli de 1 de taille 2x3x4
tensor1 = torch.ones([2,3,4])
print("tensor1 \n", tensor1)
## tenseur de zéros de taille 2x3 de type float
tensor2 = torch.zeros([2,3], dtype=torch.float)
print(tensor2)
## tirage uniforme entier entre 10 et 15,
tensor3 = torch.randint(10,15, (4,3))
print("tensor3", tensor3)
## remarquez l'utilisation du _ dans random pour l'opération inplace

## tirage suivant la loi normale
tensor4 = torch.randn(4, 4)
print("tensor4", tensor4)

## equivalent à zeros(3,4).normal_
tensor5 = torch.zeros(3,5)
tensor5.normal_()
print("tensor5", tensor5)

## Création d'un vecteur de 3 flottants selon la loi de normale

tensor6 = torch.zeros(3, dtype=torch.float)
tensor6.normal_()
print("tensor6",tensor6)
## concatenation de tenseurs sur la dimension 0
tensor7 = torch.randn(2,2)
print("tensor7",tensor7)

tensor8 = torch.ones(2,2)
tensor9 = torch.cat((tensor7, tensor8), 0)
print("tensor9", tensor9)


## concatenation de tenseurs  sur la dimension 1
tensor10 = torch.cat((tensor7, tensor8), 1)
print("tensor10", tensor10)
## Taille des tenseurs/vecteurs
print("size t10", tensor10.size())
## Conversion de type

# Opérations élémentaires sur les tenseurs
## produit scalaire (et contrairement à numpy, que produit scalaire)
tensor11 = torch.matmul(tensor7, tensor8)
print("tensor11", tensor11)

## produit matriciel : utilisation de @ ou de la fonction mm
prod1 = tensor7@tensor8
print("prod1",prod1)
## transposé

t12 = tensor7.t()
print("t12",t12)

## index du maximum selon une dimension


## somme selon une dimension/de tous les éléments


## moyenne selon  une dimension/sur tous les éléments

## changer les dimensions du tenseur (la taille totale doit être inchangée)

## somme/produit/puissance termes a termes

## Soit un tenseur a de (2,3,4). Le recopier dans une version (2,3,3,4) avec les tenseurs (3,4)
## a[0] et a[1] recopiés chacun 3 fois (avec expand)



## attention ! comme sous numpy, il peut y avoir des pièges !
## Vérifier toujours les dimensions !!
a=torch.zeros(5,1)
b = torch.zeros(5)
print(a,b)
## la première opération fait un broadcast et le résultat est 1 tenseur à 2 dimensions,
## le résultat de la deuxième opération est une matrice contenant un vecteur unique
print(a-b,a.t()-b)

tensor1 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor3 tensor([[13, 12, 10],
        [12, 10, 10],
        [12, 12, 14],
        [11, 14, 13]])
tensor4 tensor([[ 0.6410, -0.1512, -0.6423, -0.8848],
        [-0.2711,  2.1119, -0.8357,  0.3346],
        [-0.0977,  0.5708, -0.8523, -0.8876],
        [-1.1480,  0.4593, -0.2570, -1.0007]])
tensor5 tensor([[-1.3739,  0.3977,  0.4899, -1.9445, -0.5142],
        [ 0.7341,  0.4911,  0.1478,  0.5721, -0.4801],
        [ 1.4872,  0.4851,  0.1950, -0.1775, -0.3851]])
tensor6 tensor([1.3422e+00, 1.6363e+00, 4.9968e-04])
tensor7 tensor([[0.7468, 1.0905],
        [1.1018, 2.4997]])
tensor9 tensor([[0.7468, 1.0905],
        [1.1018, 2.4997],
        [1.0000, 1.0000],
        [1.0000, 1.0000]])
tensor10 tensor([[0.7468, 1.0905, 1.0000, 1.0000],
        [1.1018, 2.4997, 1.0000, 1.00

### <span class="alert-success"> Exercice :   Régression linéaire  </span>

On souhaite apprendre un modèle de régression linéaire $f$ du type:  $f(x,w,b)=x.w^t+b$  avec $x\in \mathbb{R}^{{d}}$ un vecteur d'observations pour lequel on souhaite prédire une sortie $\hat{y} \in \mathbb{R}$, $w\in\mathbb{R}^{1,d}$ et $b\in \mathbb{R}$ les paramètres du modèle.

Pour cela on dispose d'un jeu de données étiquetées $\{(x,y)\}$, que l'on découpe en jeu d'entraînement (80%) et de validation (20%). Dans cet exercice, on utilisera le jeu de données très classique *Boston*, le prix des loyers à Boston en fonction de caractéristiques socio-économiques des quartiers.

On considèrera un coût moindres carrés pour apprendre le modèle sur le jeu d'entraînement (avec $N$ le nombre de données d'entraînement et $(x^i,y^i)$ le i-ème couple de cet ensemble): $$w^∗,b^∗=argmin_{w,b}\frac{1}{N} \sum_{i=1}^N \|f(x^i,w,b)-y^i\|^2$$


* Définir (en version tensorielle PyTorch) la fonction **flineaire(x,w,b)** qui calcule $f(x,w,b)=x.w^t+b$  avec $x\in \mathbb{R}^{{n\times d}},~w\in\mathbb{R}^{1,d}, b\in \mathbb{R}$
* Donner le code d'une fonction **loss(x,w,b,y)** qui retourne le coût moindre carré du modèle linéaire utilisant **flineaire(x,w,b)** pour un batch de données $x$ et leurs images associées $y$.
* Calculer le gradient de l'erreur en fonction de chacun des paramètres $w_i$ et b. Donner le code d'une fonction **getGradient(x,w,b)** (commencer éventuellement avec des boucles avant de réaliser la version matricielle plus efficace).
* Complétez le code ci-dessous pour réaliser une descente de gradient et apprendre les paramètres optimaux de la regression linéaire.
* Modifier le code ci-dessous pour n'entraîner que sur 80% des données et se tester sur 20%



Attention !
* l'algorithme doit converger avec la valeur de epsilon fixée; si ce n'est pas le cas, il y a une erreur (la plupart du temps au niveau du calcul du coût).

In [49]:
def flineaire(x,w,b):
    ## [[student]]
    return (x @ w.T) +b

    ## [[/student]]
z

def getLoss(x,w,b,y):
    ## [[student]]
    y_pred= flineaire(x,w,b)
    return torch.mean((y - y_pred)**2)
    ## [[/student]]


def getGradient(x,w,b,y):
    ## [[student]]
    return 0
    ## [[/student]]






In [50]:

## Chargement des données California et transformation en tensor.
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing() ## chargement des données
data_x = torch.tensor(housing['data'],dtype=torch.float)
data_y = torch.tensor(housing['target'],dtype=torch.float)

print("Nombre d'exemples : ",data_x.size(0), "Dimension : ",data_x.size(1))
#print(data_x,data_y)


torch.random.manual_seed(1)

#initialisation aléatoire de w et b
w = torch.randn(1,data_x.size(1),requires_grad=True)
b =  torch.randn(1,1,requires_grad=True)




## [[student]]
print(flineaire(data_x,w,b))
print(getLoss(data_x,w,b,data_y))
## [[/student]]



EPOCHS = 100000
EPS = 1e-7
#for i in range(EPOCHS):
    ## [[student]]

    ## [[/student]]

Nombre d'exemples :  20640 Dimension :  8
tensor([[ -233.7849],
        [-1178.6215],
        [ -310.0745],
        ...,
        [ -556.1147],
        [ -435.4949],
        [ -727.5859]], grad_fn=<AddBackward0>)
tensor(805029.2500, grad_fn=<MeanBackward0>)
